* Cultivation and Mastery

Cultivation is the path of increased Mastery.
  - Cultivation need never end
  - The rewards of Cultivation increase endlessly

A Learner is naturally interested in acquiring Mastery of their areas of
interest. A Learner who becomes a Cultivator becomes an Extraordinary Learner.

Mastery and Cultivation are rewarded with
- Increased Capabilities
- Increased Understanding
      - Depth, Breadth, Scope
      - Interconnection, Consilience, Unification
- Pleasure, i.e. /Intrinsic Motivation/
- Access to more learning and cultivation opportunities

** Pitfalls

There are illusions and confusions: false seemings which appear to block the
path of Mastery and Cultivation. It's good to have experienced others who one
can consult when one's paths seem to be blocked.

*** Signs of Illusory Barriers

It seems you've run out of more things to learn
- You're confused, seek guidance!

It seems to be too hard!
- You've missed the easier paths, seek guidance!

It seems to be getting more and more complicated!
- It's time to /integrate what you've learned/
- /Increasing understanding unifies and simplifies/
- Seek guidance and partnership!

*** Extrinsic Motivation

Excessive focus on Extrinsic Motivation will undermine Intrinsic Motivation and
your Cultivation will wither!

Examples of Extrinsic Motivation
- Certifications
- A focus only on practical utility
- Increased Social and Economic Rewards
- Ability to dominate others with our superiority
