* Open Content

Much of the progress enriching the modern world is a result of sharing knowledge
and tools rather than keeping such proprietary in the manner of Medieval Guilds
or encumbered with limiting commercial licenses affordable only by a few.

It is essential for materials used by Learners to be freely shareable and
continue to be available after becoming an integral part of their practice.
Thus, the League of Extraordinary Learners prioritizes Open Content materials.

It is almost as essential for those materials to be freely modifiable so that we
can improve, adapt and evolve them for better use. Licenses which require
attribution, e.g. via small invariant sections are acceptable.

Ideally these materials would exist in full source form, e.g.
- exist in public Git repositories with history and all explored variations
- consist of components which can be re-rendered and re-mixed
      - separate audio track
      - separate video overlays
      - source code which generates media procedurally

Open (and Freely Shareable) Culture Links
- [[https://web.archive.org/web/20210506215626/https://creativecommonsusa.org/index.php/open-culture][Open Culture]]
- [[https://en.wikipedia.org/wiki/Free-culture_movement][Wikipedia: Free-Culture]]
      - [[https://creativecommons.org][The Creative Commons]]
- [[https://en.wikipedia.org/wiki/Free_and_open-source_software][Wikipedia: Free and Open-Source Software]]
      - [[https://www.fsf.org][The Free Software Foundation]]
      - [[https://directory.fsf.org/wiki/Main_Page][The Free Software Directory]]
      - [[https://www.gnu.org][The GNU Project]]
      - [[https://distrowatch.com][DistroWatch - Operating Systems]]
- [[https://www.eff.org][The Electronic Frontier Foundation]]
- [[https://en.wikipedia.org/wiki/Open-source_hardware][Wikipedia: Open Source Hardware]]
