* Native Readers

** What is a Native Reader?

Native readers learn Reading without instruction but through exposure,
by being read to when young.  This is similar to how Native Speakers
learn to understand and speak their native language by being immersed
in that language when young.

** How Is This Possible?

Learning through exposure means learning by virtue of the natural
function of the language centers of their brain, directed by but not
managed by conscious attention.

Consider:
- Native Speakers are always fluent in their native language after a
  few years of exposure.
- People who've studied a foreign language in school for a few years
  are rarely fluent.

** Native Readers Usually Read Much Better!

Native Readers
- read more quantity and quality of reading material
- read effortlessly yet more actively
- read faster and with better comprehension
- retain more knowledge from what they read

Non-Native Readers typically
- Devote part of their conscious attention to the mechanics of
  reading: Sounding out words, navigating through the structure of
  sentences and paragraphs, etc.
- Leaving less attentional resources to the content they're reading.
  - Retaining a whole paragraph in working memory is difficult.
- Have smaller vocabularies
  - unfamiliar words disrupt the reading process
  - make more sophisticated reading material burdensome

Native Readers require no conscious attention to the mechanics of
reading.  It's automatic and effortless, handled by their brain's
unconscious language centers.  Assuming normal or corrected vision,
Native Readers do not get tired, do not get headaches or have any
other discomfort reading.

Reading faster with high comprehension and retention means
- Two to three times faster than non-native readers.
- Two to three times faster than spoken language.
- Some people read even faster - without skimming!

Native Readers have an enormous advantage in general learning and
education programs.

** Is It Too Late for Non-Native Readers?

- Most people who learn foreign languages in school are far from fluent!
- Most people who learn reading in school are far from native readers!

So is it too late? - NO!

In both cases you have to learn to transfer the management of the
"skill" from your Conscious Mind (which has very limited resources) to
your language centers which are built for this sort of work.

The Conscious Mind is a very small part of the whole mind.  The whole
mind contains many subsystems which have much more capacity than the
conscious mind, although for specialized kind of material.
- See [[https://en.wikipedia.org/wiki/Society_of_Mind][The Society of Mind by Marvin Minsky]]

One of the pitfalls of using the limited resources of the conscious
mind to deal with language is that one gets used to skimming, focusing
on some of the content words and guessing at the overall meaning.
This is noticable in many foreign language speakers as well as many
readers.  It's a difficult habit to break out of, because of our
impatience.

See [[*Adults Can Learn the Same Way!][Adults Can Learn the Same Way!]] below!

** Recommendations

*** Read to Young Children!

Children can become Native Readers as early as two and a half years
old!

*** Find Materials That Engage Learners!

Facilitators can facilitate Native Reading by
1. Finding materials which strongly engage the learner
   - Any "children's books" should also be interesting to adults!
   - Avoid anything infantile, i.e. not respecting the learner as an
     intelligent being!
2. Seeking diversity of reading material which engage the learner
4. Moving the reading level up as the learner's engagement allows.

In Japan, which has a very high level of reading (in 4 writing
systems!) there is no social stigma against anyone of any age reading
comic books.  Comic books and other books with integrated text and
graphics are especially valuable for beginning learners!

*** Adults Can Learn the Same Way!

For adults who are poor readers or are learning to read in a new language
- Find simply-written books on topics you find fascinating
  - Airplanes, animals, sports, whatever you love!
- Childrens' books that adults love too!
- Magazine and newspaper articles are easier than long books!
- Progressive readers designed for language learners.
  - These are great, containing short articles and stories with
    vocabulary and other forms of complexity increasing gradually.
    
Adults can be coached to use their conscious attention to focus on the
material without trying to consciously engage in the mechanics of
reading.

Adopt a dynamic pace
- Read as fast as comfortably possible but without skimming
  - Take in each sentence as a whole.
  - Notice every aspect of its meaning.
  - As that becomes automatic, do the same with paragraphs!
- Slow down and re-read when you encounter a harder bit.
- Then speed up as soon as it's easier!
- Don't worry about unfamiliar words or idioms if you are still
  "following the story".

Tip: Read with an unabridged audio accompaniment!

If the material is in a new language, have the same book available in
a familiar language.  Glance at the corresponding material in the
familiar language anytime you've "lost the story".

*** Avoid Teaching Conscious Techniques Early

Phonics, Speed Reading and other approaches to teaching reading as a
skill requiring conscious attention should be avoided until after the
learner's reading ability is well developed and stable.

- Do NOT try to recognize out words from the sounds of their letters!
- Instead:
  - Look at the word with interest and curiosity.
  - Allow your language centers to either recognize it or not.
    - In time, it will do so automatically!

Again: You may find it helpful to read with an unabridged audio
accompaniment!

Despite its severely restricted capacities, conscious awareness is the
key to engaging the other subsystems of the mind.  Just as the
conductor of an orchestra directs the flow of the players rather than
trying to take over any of the playing.

Once your new normal is reading comfortably without conscious
attention, you may possibly benefit from consciously studying such
things as phonics, speed reading techniques, etc., if you refrain from
trying to directly applying such knowledge consciously but instead
allow your conscious awareness to bring these enriching aspects of the
written word to your language centers.

** Synonyms:
- Native Reader
- Spontaneous Reader
- Self-Taught Reader
- Hyperlexia

** Links

- [[https://www.psychologytoday.com/us/blog/freedom-to-learn/201002/children-teach-themselves-to-read][Children Teach Themselves to Read]] :: The unschoolers' account of how children learn to read (Psychology Today)

- [[https://en.wikipedia.org/wiki/Hyperlexia][Hyperlexia]]
[[https://en.wikipedia.org/wiki/Autodidacticism][- Autodidacticism]]
- [[https://spontaneousreading.wordpress.com/][Spontaneous Reading Consultant]]
