* LOEL Introductory Video: Context

An interview of Greg Davidson by Lynn Dobbs.

** The intention of this video

*** Lynn

Welcome, Dear Viewer: I'm looking forward to sharing with you the gist of some
  rich conversations which Greg and I have been having.

Greg, what do you want to accomplish with this first video?

*** Greg

I've been working on a new educational system which puts Learners First. and
I've been running into Paradigms in our society which limit what's possible.

In this video I'd like to reveal those Paradigms and related Contexts so that we
have the awareness to create outside of traditional limits.  

** Context and Paradigm

*** Lynn

What do you mean by Paradigm and by context?

*** Greg

Earlier we were talking about them and we got some confusions about Paradigms
and Contexts, so we looked them up.  Lynn, would you read the first two definitions
of what we found for Context in the Mirriam-Webster Dictionary?

*** Lynn

Sure:
1. The parts of a discourse that surround a word or passage and can throw light
   on its meaning.
2. the interrelated conditions in which something exists or occurs: environment,
   setting, the historical context of a war, and so forth.

*** Greg

You get this notice that a Context is something additional, that is surrounding
something, giving it meaning.

A context could be explicit, where you could point to it.

Or it might be in the background, unspoken, not something which we are
consciously aware of, yet still influencing the meaning of things.

Does the dictionary say anything else?

*** Lynn

Yes, it goes on to say:
#+begin_quote
Context now most commonly refers to the environment or setting in which
  something (whether words or events) exists. When we say that something is
  contextualized, we mean that it is placed in an appropriate setting, one in
  which it may be properly considered.
#+end_quote

*** Greg

There we go: Properly considered, or sometimes improperly considered or not
considered at all!

Ideally contexts would be explicit and consciously noticed. But they are often
implicit and not consciously noticed.  In that case the meanings which they
determine simply occurs as "the truth" or just "they way things are".

Lynn, would you read what the American Heritage dictionary says about Paradigm:

*** Lynn

#+begin_quote
A set of assumptions, concepts, values and practices that constitute a way of
  viewing reality for the community that shares them.
#+end_quote

*** Greg

There we go. Paradigms are the Bigger, Broader Contexts at the level of our
community or society. We generally don't consciously notice them, even as they
determine our assumptions, understanding, values and what appears to be reality.

Before we can think freely or act freely, we have to get clear about any
existing Contexts which are influencing us. Any contexts which we're not aware
of will tend to do our thinking for us!

** Changing Contexts Change Content and Relationships!

*** Greg

Consider what everyone knew for thousands of years:
- If you want your children to turn out well you need to
      - punish them when they don't do what you tell them to do
      - and when they do what you told them /not to do/.
- Teachers frequently doled out punishment to discipline their
  students.
- Employers used punishment to keep their employees in line.
- And so on.

It was rarely said explicitly, but the context of punishment-is-good
  was part of the context for
- "Child rearing"
- "Teaching"
- "Management"
- "Spousal relations"
- "Animal training".
- Wherever there was someone with "power over" another.

Successful character development involved "discipline" in the form of
  punishment.
- Self-Discipline and good habits were supposed to emerge from the
  internalization of the fear of punishment.
- Respect for authority meant being properly afraid of punishment from those
  with power over us.

*** Lynn

That reminds me of the phrase "Fear of God".

*** Greg

Yup! Fear was supposed to be good for people's development. Then
  research studies started to show that negative reinforcement is generally
  counterproductive. Reformers combined the results of this research with moral
  arguments to argue against the use of punishment. The old "paradigm" was
  weakened and a new paradigm began to emerge - and is still emerging.

*** Lynn

What is this new paradigm, what are the new contexts?

*** Greg

Part of the emerging paradigm is the possibility of partnership.
- Partnership is now the ideal in spousal relationships.
- In employer/employee relationships we now hear a lot about team and
  partnership - and where this becomes real, productivity increases.
- Reformed parent/child and teacher/student relationships now have little
  or no physical punishments
      - but they are not good examples of partnership!

*** Lynn

I'm hear you saying that the new context for spousal relationships is
  partnership and that this context works best for employer/employee
  relationships as well - though this is maybe a work in progress. But I think
  I'm hearing you say that the context in our society for parent/child and
  teacher/student relationships is /not/ partnership? So what is it?

*** Greg

In modern urban societies where we have ended child labor we tend to
  infantilize our children. They have no meaningful role in the family. We care
  about them but we treat them like pets while waiting for them to magically
  turn into human beings and leave us.

In most institutional schools the context is that the administrators
  tell the teachers what to do and the teachers tell the students what to do.
  It's the traditional Dominator Paradigm, just without the physical punishment.
  Psychological punishment such as humiliation and the constant fear of judgment
  and failure are the norm. The results are learned helplessness and generally
  disappointing educational outcomes.

*** Lynn

Wow, that sounds pretty grim.  Is anything changing?

*** Greg

There are a number of parents and schools trying to turn this around,
  including home schoolers, unschoolers, Montessori schools, mastery learning
  and /The League of Extraordinary Learners/! That will be the topic of another
  video. All of this material is availble in text form with lots more details on
  the website tloel.org [[https://tloel.org][The League of Extraordinary Learners]].

** References

- [[https://www.merriam-webster.com/dictionary/context][Merriam-Webster Dictionary: context]]
- [[https://en.wikipedia.org/wiki/Dominator_culture][Wikipedia: Dominator Culture]]
- [[https://en.wikipedia.org/wiki/Unschooling][Wikipedia: Unschooing]]
- [[https://en.wikipedia.org/wiki/Montessori_education][Wikipedia: Montessori Education]]
- [[https://en.wikipedia.org/wiki/Mastery_learning][Wikipedia: Mastery Learning]]
