* Introductory Video: A Context for The LOEL

An interview of Greg Davidson by Lynn Dobbs about
- the context behind
- /The League of Extraordinary Learners/.

** The intention of this video

- Lynn [without Greg] :: My name is Lynn.  I'm looking forward to
  sharing some rich conversations which my friend Greg and I have been
  having.
- Lynn [with Greg] ::  Let me introduce Greg to you.  Greg has a deep
  understanding of many things including human nature, science, and
  creating a future worth living into.
- Lynn :: Greg, what do you want to accomplish with this video?
  
- Greg :: I want to share the context behind a new initiative
  - /The League of Extraordinary Learners/.

** Context and Paradigm

- Lynn :: What do you mean by /Context/?
  
- Greg :: Ha! That's the first thing we need to talk about! I remember
  that we argued a bit about it in one of our earlier
  conversations. What did we find when we looked in the dictionary?
  
- Lynn :: Merriam-Webster gave two definitions:
      - Definition 1 :: The parts of a discourse that surround a word
        or passage and can throw light on its meaning.
      - Definition 2 :: The interrelated conditions in which something
        exists or occurs: environment, setting.
	 
- Greg :: Okay! The first definition is about Explicit Context, where you can
  point to a part of a text which provides context for another part.
- Greg :: I'm more interested in the second definition, where the context is
  implicit, where we don't consciously notice it yet it influences our
  understanding of things.
- Greg :: Does the dictionary say anything else?
  
- Lynn :: Yes, it goes on to say:
      - "Context now most commonly refers to the environment or
        setting in which something (whether words or events)
        exists. When we say that something is contextualized, we mean
        that it is placed in an appropriate setting, *one in which it
        may be properly considered*."
	
- Greg :: Yeah: Properly considered - or maybe improperly considered
  or not considered at all without our being aware of that context
  influencing us!
- Greg :: I want to talk about the contexts which have informed our
  understanding of human relationships and then I'll focus on
  relationships in Education. 
- Greg :: I'd like to use two more fancy words: /Paradigm/ and
  /Model/.  Lynn, would you read what the American Heritage Dictionary
  says about /Paradigm?/

- Lynn :: Sure:
  #+begin_quote
A set of assumptions, concepts, values and practices that constitute a way of
  viewing reality for the community that shares them.
#+end_quote

-Greg :: There we go. Paradigms are the Bigger, Broader Contexts at
the level of our Community or Society.  They are a key part of what we
call /Culture/.
- Greg :: One more: What does the American Heritage Dictionary say
  about /Model/ as a description of a system or phenomenon?

- Lynn :: Okay, that's the 3rd definition:
#+begin_quote
A schematic description or representation of something, especially a
system or phenomenon, that accounts for its properties and is used to
study its characteristics, e.g.
  - a model of an atom
  - an economic model
#+end_quote

- Greg :: Thanks!  Note that a /Model/ doesn't have to be the complete
  truth about something - like we ever know that! - it just has to
  help us understand something.

** Changing Contexts Change Content and Relationships!

- Greg :: I'm going to be introducing two key /Paradigms/ which I
  learned from /Riane Eisler/
  - the Dominator Paradigm :: exercising power /over/ another person
    or persons
  - the Partnership Paradigm :: sharing power /with/ one or more
    others

- Greg :: Consider what everyone knew for thousands of years:
      - If you want your children to turn out well you need to
            - punish them when /they don't do/ what you tell them to
            - and punish them when they do /what you told them *not* to/.
      - Traditionally Teachers routinely used physical punishment to
        discipline their students to make them learn properly.
      - Employers also traditionally used intimidation and a variety
        of punishments to keep their employees in line.
- Greg :: Although it was rarely said explicitly, the context of
  punishment-is-good-for-you, a classic part of the /Dominator
  Paradigm/, showed up strongly in nearly every area of life
      - "Child rearing"
      - "Teaching"
      - "Management"
      - "Spousal relations"
      - "Animal training".
      - Wherever there was someone with "power over" another.
- Greg :: Successful character development was supposed to follow the
  internalization of the fear of punishment: supposedly building
  "self-discipline" and good habits. "Respect for authority" was
  supposed to follow being properly terrified of punishment from those
  with power over us.
  
- Lynn :: That reminds me of the phrase "Fear of God" that I was
  taught, without a context, in Lutheran School as a child.
  
- Greg :: Yup! Fear was supposed to be good for people's
  development. But when social science researchers tried to measure
  this "benefit", their studies instead showed that any amount of
  negative reinforcement is generally counterproductive. Reformers
  used these results along with moral arguments to argue against the
  use of punishment. This has gradually been weakening the Dominator
  Paradigm and a new paradigm began to emerge - and is still emerging.
  
- Lynn :: What is this new paradigm, what are the new contexts?
  
- Greg :: Part of the emerging paradigm is the possibility of
  partnership, what /Riane Eisler/ calls the /Partnership Paradigm/.
      - Partnership is now the ideal in spousal relationships.
      - In employer/employee relationships we now hear a lot about
        team and partnership - and where this is more than empty
        rhetoric, productivity increases.
      - Reformed parent/child and teacher/student relationships now have little
        or no physical punishments
            - but they are not good examples of partnership!
	      
- Lynn :: I'm hearing you saying that the new context for spousal relationships is
  partnership and that this context works best for employer/employee
  relationships as well - though this is maybe a work in progress. But I think
  I'm hearing you say that the context in our society for parent/child and
  teacher/student relationships is /not/ partnership? So what is it?
  
- Greg :: In modern urban societies where we have ended child labor we
  tend to infantilize our children. They consume resources rather than
  helping produce them. We care about them but we treat them like pets
  while waiting for them to magically turn into human beings and leave us.

- Greg :: In the 19th Century the United States and many other modern
  countries based their formal education systems on the /Prussian
  Education System/ which was developed to prepare boys for military
  service by training them to obey authority without question.  It
  came up with new ideas such as
  1. Dividing the students into age cohorts.  Everyone of the same age
     should learn the same material at the same rate.
  2. Divide all educational material into subjects and divide each
     subject into fixed-length chunks.
  3. Use bells to start and end each chunk after which the students
     run to another room to get a chunk on an unrelated subject from
     another instructor.
  4. Frequently evaluate the students on their acquisition of the
     material and put that on the student's permanent record.
  5. And other "innovative practices" - [heavy sarcasm]!
     
- Greg :: This is a /Top-Down/ system, part of /Dominator Culture/.
  It's based on a hierarchy: administrators tell the teachers how to
  go about educating the students - despite having no experience
  teaching.  The teachers deliver approved lectures, assignments and
  tests to the students.  The teachers then grade the student's
  assignments and tests which become part of a final grade in the
  student's permanent record as proof of the worth of that student.
  These grades as the basis for future educational and employment
  opportunities.  The only thing that's changed in the last 100 years
  is that teachers and administrators no longer use physical
  punishment as part of the indoctrination and control.  Instead, they
  use psychological punishment such as humiliation in front of their
  peers and the constant fear of judgment and failure.  The results
  are learned helplessness and overall disappointing educational
  outcomes.
  
- Lynn :: Wow, that sounds pretty grim.  Is anything changing?

- Greg :: Many modern schools are attempting to reform teaching
  methods, but they struggle with the flaw of their fundamental
  paradigm.  It's hard to change what you're doing when you aren't
  changing your context - where you're /coming from/.  Some parents
  opt their children out of school entirely, in favor of home
  schooling and other forms of unschooling.  But there are a few
  alternative schools which do /not/ operate inside of the Dominator
  Model, for example Montessori Schools.

- Lynn :: I love Montessori Schools, but tell us why you think they're
  important.

- Greg :: Maria Montessori is another of our heros.  She believed that
  children were naturally motivated to learn, without any need to try
  to compell them.  She also believed that "children are better at
  learning than teachers are at teaching".  Instead of developing /a
  teaching system/, she developed /a learning system/, consisting of
  classrooms full of interactive learning materials designed to
  provide natural feedback to a child working with them.  A Montessori
  classroom has a trained facilitator in the classroom (she called
  them "Directresses") rather than a teacher.  A key distinction is
  that a facilitator is a resource for the child, not an intermediary
  like a teacher.  A facilitator sits to the side, rather than
  standing in front.

- Lynn :: How available is Montessori Education today?

- Greg :: Montessori started her schools in some of the poorest areas
  of her day, including the vast slums of Rome and of Calcutta - then
  the administrative capital of India: This was possible because
  Montessori schools are designed to be cheaper to run than
  conventional schools!  And even with the poorest students,
  Montessori schools consistently produced better results than regular
  schools.  Yet somehow after her death the Montessori schools
  available to the poor have largely disappeared.  Most Montessori
  Schools today are expensive private schools serving the wealthy
  elite.  And indeed, many of today's elite come from Montessori
  Schools, like the founders of Google.  Note that this sort of change
  is a classic example of /Dominator Culture/ in action!

- Lynn :: Do you have a plan for fixing this?

- Greg :: Yes, but first there's one more system I'd like to mention,
  /Mastery Learning/.  I encountered this at the University of
  California in the late 1970s and early 1980s - I later learned that
  it was being tried out by innovative educators worldwide at that
  time.  In Mastery Education the material to be learned is divided up
  into logical modules accompanied by self-paced interactive exercises
  and self-assessment tests.  The exercises can be done alone or with
  partners.  The exercises and tests are designed only to assist the
  learners in mastering each module before moving on - their results
  do not go on any permanent record.  What we observed is that instead
  of hating tests, the students in the Mastery Learning courses loved
  them: they could hardly wait to take the next test!  And when we
  measured their accomplishments at the end of the term against
  students taking the older conventional version of the course: 80% of
  the Mastery students scored at the level of a high "A" whereas only
  about 15% of the students coming out of the conventional version of
  those courses got any kind of an "A".

- Greg :: We also learned two more things: Students who completed the
  new courses the previous year were better facilitators for the new
  students than so-called "experts" in the subject.  And those "peer
  facilitators" were also better at improving the learning materials!
  Do you see /Partnership Culture/ involved here?

- Lynn :: Defintely!  So is your plan to create new schools combining
  the Montessori and Mastery systems?  That sounds great but also
  pretty ambitious!

- Greg :: Well, physical classrooms have a lot of overhead, and
  there's no way that any physical school: Prussian, Montesssori,
  Mastery or anything else can adequately cover all of the subjects
  which Learners want to Learn.  The biggest new trend is to move
  educational activities and materials online.  While most of these
  materials, especially lectures, still follow a top-down model, they
  can often be placed in a more Learner-centric context by paring them
  with interactive materials and a network of resources, including
  fellow students and Peer Facilitators.  We don't want to replicate a
  classroom experience but to meet the Learners where they are with
  subjects, materials and resources they choose.  And after using
  these on-line resources to learn something, they will be offered the
  opportunity to be a facilitator for a few learners coming up behind.
  We have built-in mechanisms for students and peer facilitators to
  provide feedback on all of our materials, and peer facilitators will
  also have an opportunity to revise existing materials.

- Lynn :: I like the idea of that, but I'm not so sure that someone
  who just learned something is a substitute for an actual expert!

- Greg :: Oh, we'll have experts, but their job is to /facilitate/ the
  development process rather than to control it top-down.  We intend
  to provide some more in-depth videos about The LOEL and how it all
  works in the near future.  In the meantime, you can visit /The
  League of Extraordinary Learners/ website: T-L-O-E-L DOT org.

- Lynn :: I really like what you say, Greg.  I look forward to working
  with you on further videos.
- Lynn [without Greg] :: Stay tuned!  More videos to come.  Please
  consider what we talked about in this one and figure out if you are
  operating from a /Dominator Model/ or a /Partnership Model/ and
  which one do you want to live in to?

** References

- [[https://www.merriam-webster.com/dictionary/context][Merriam-Webster Dictionary: context]]
- [[https://en.wikipedia.org/wiki/Dominator_culture][Wikipedia: Dominator Culture]]
- [[https://en.wikipedia.org/wiki/Unschooling][Wikipedia: Unschooing]]
- [[https://en.wikipedia.org/wiki/Montessori_education][Wikipedia: Montessori Education]]
- [[https://en.wikipedia.org/wiki/Mastery_learning][Wikipedia: Mastery Learning]]
- [[https://en.wikipedia.org/wiki/Prussian_education_system][Prussian education system]]
** Currently Deleted Scenes

Greg brought back having Lynn look up Paradigm and Model!
