* Introductory Video: A Context for The LOEL
:PROPERTIES:
:ID:       71d6aa43-e96a-48ed-9976-65d5589ad2b8
:END:

An interview of Greg Davidson by Lynn Dobbs about
- the context behind
- /The League of Extraordinary Learners/.

** The intention of this video

- Lynn [without Greg] :: My name is Lynn.  I'm looking forward to
  sharing some rich conversations which my friend Greg and I have been
  having.

- GREG :: And we're actually in the same physical space, which is a
  great privilege!
  
- Lynn [with Greg] ::  Let me introduce Greg to you.  Greg has a deep
  understanding of many things including human nature, science, and
  creating a future worth living into.

- Lynn :: Greg, what do you want to accomplish with this video?
  
- Greg :: I want to share the context behind a new initiative
  - /The League of Extraordinary Learners/.

** Context and Paradigm

- Lynn :: What do you mean by /Context/?
  
- Greg :: Ha! That's the first thing we need to talk about! I remember
  that we argued a bit about it in one of our earlier
  conversations. What did we find when we looked in the dictionary?
  
- Lynn :: Merriam-Webster gave two definitions:
      - Definition 1 :: The parts of a discourse that surround a word
        or passage and can throw light on its meaning.
      - Definition 2 :: The interrelated conditions in which something
        exists or occurs: the environment or setting.
	 
- Greg :: Okay! The first definition is about Explicit Context, where you can
  point to a part of a text which provides context for another part.
- Greg :: I'm more interested in the second definition, where the context is
  implicit, where we don't consciously notice it yet it influences our
  understanding of things.
- Greg :: Does the dictionary say anything else?
  
- Lynn :: Yes, it goes on to say:
      - "Context now most commonly refers to the environment or
        setting in which something (whether words or events)
        exists. When we say that something is contextualized, we mean
        that it is placed in an appropriate setting, *one in which it
        may be properly considered*."
	
- Greg :: Yeah: Properly considered - or maybe improperly considered
  or not considered at all without our being aware of that context
  influencing us!
- Greg :: I want to talk about the contexts which have informed our
  understanding of human relationships and then I'll focus on
  relationships in Education. 
- Greg :: I'd like to use two more fancy words: /Paradigm/ and
  /Model/.  Lynn, would you read what the American Heritage Dictionary
  says about /Paradigm?/

- Lynn :: Sure:
  - Paradigm :: A set of assumptions, concepts, values and practices
    that constitute a way of viewing reality for the community that
    shares them.

-Greg :: There we go. Paradigms are the Bigger, Broader Contexts at
the level of our Community or Society.  They are a key part of what we
call /Culture/.
- Greg :: One more: What does the American Heritage Dictionary say
  about /Model/ as a description of a system or phenomenon?

- Lynn :: Okay, that's the 3rd definition:
  - Model :: A schematic description or representation of something,
    especially a system or phenomenon, that accounts for its
    properties and is used to study its characteristics, for example
    - a model of an atom
    - an economic model

- Greg :: Thanks!  Note that a /Model/ doesn't have to be the complete
  truth about something - like we ever know that! - it just has to
  help us understand something.

- Lynn :: Reminds me of a great quote, "All models are false, and some are useful."

- Greg :: Ha! I used to hate that quote - and now I love it!
  - Now I have the right context for it!

** Changing Contexts Change Content and Relationships!

- Greg :: I'm going to be introducing two key /Paradigms/ which I
  learned from /Riane Eisler/
  - the Dominator Paradigm :: where the powerful exercise their /power
    over/ other people in in /win-lose/ interactions.
  - the Partnership Paradigm :: where people work tegether, combining
    their /power together/ for the gain of all in /win-win/
    interactions.

- Greg :: Consider what everyone knew for thousands of years:
      - If you want your children to turn out well you need to
            - punish them when /they don't do/ what you tell them to
            - and punish them when they do /what you told them *not* to/.
      - Traditionally Teachers routinely used physical punishment to
        discipline their students to make them learn properly.
      - Employers also traditionally used intimidation and a variety
        of punishments to keep their employees in line.
- Greg :: Although it was rarely said explicitly, the context of
  punishment-is-good-for-you, a classic part of the /Dominator
  Paradigm/, showed up strongly in nearly every area of life
      - "Child rearing"
      - "Teaching"
      - "Management"
      - "Spousal relations"
      - "Animal training".
      - Wherever there was someone with /power over/ another.
- Greg :: Successful character development was supposed to follow the
  internalization of the fear of punishment: supposedly building
  /self-discipline/ and good habits. /Respect for authority/ was
  supposed to follow being properly terrified of punishment from those
  with power over us.
  
- Lynn :: That reminds me of the phrase /Fear of God/ that I was
  taught, without a context, in Lutheran School as a child.
  
- Greg :: Yup! Fear was supposed to be good for people's
  development. But when social science researchers tried to measure
  this "benefit", their studies instead showed that any amount of
  negative reinforcement is generally counterproductive. Reformers
  used these results along with moral arguments to argue against the
  use of punishment. This has gradually been weakening the Dominator
  Paradigm and a new paradigm began to emerge - and is still emerging.
  
- Lynn :: What is this new paradigm, what are the new contexts?
  
- Greg :: Part of the emerging paradigm is the possibility of
  partnership, what /Riane Eisler/ calls the /Partnership Paradigm/.
      - Partnership is now the ideal in spousal relationships.
      - In employer/employee relationships we now hear a lot about
        team and partnership - and where this is more than empty
        rhetoric, productivity increases.
      - Reformed parent/child and teacher/student relationships now have little
        or no physical punishments
            - but they are not good examples of partnership!
	      
- Lynn :: I'm hearing you saying that the new context for spousal relationships is
  partnership and that this context works best for employer/employee
  relationships as well - though this is maybe a work in progress. But I think
  I'm hearing you say that the context in our society for parent/child and
  teacher/student relationships is /not/ partnership? So what is it?
  
- Greg :: In modern urban societies where we have ended child labor we
  tend to infantilize our children. They consume resources rather than
  helping produce them. We care about them but we treat them like pets
  while waiting for them to magically turn into human beings and leave us.

- Greg :: In the 19th Century the United States and many other modern
  countries based their formal education systems on the /Prussian
  Education System/ which was developed to prepare boys for military
  service by training them to obey authority without question.  It
  came up with new ideas such as
  1. Dividing the students into age cohorts.  Everyone of the same age
     should learn the same material at the same rate.
  2. Divide all educational material into subjects and divide each
     subject into fixed-length chunks.
  3. Use bells to start and end each chunk after which the students
     run to another room to get a chunk on an unrelated subject from
     another instructor.
  4. Frequently evaluate the students on their acquisition of the
     material and put that on the student's permanent record.
  5. And other "innovative practices" - [heavy sarcasm]!
     
- Greg :: This is a /Top-Down/ system, part of /Dominator Culture/.
  It's based on a hierarchy:
  -  administrators tell the teachers how to go about educating the students
     - despite having no experience teaching.
  -  The teachers deliver approved lectures, assignments and
     tests to the students.
  -  The teachers then grade the student's assignments and tests which
    become part of a final grade in the student's permanent record as
    proof of the worth of that student.
  - These grades as the basis for future educational and employment
    opportunities.
- Greg ::  The only thing that's changed in the last 100 years is that:
  - Teachers and administrators no longer use physical punishment as
    part of the indoctrination and control.
  - Instead, they use psychological punishment such as humiliation in
    front of their peers and the constant fear of judgment and
    failure.
  - The results are learned helplessness and overall disappointing
    educational outcomes.
  
- Lynn :: Wow, that sounds pretty grim.  Is anything changing?

- Greg :: Many modern schools are attempting to reform teaching
  methods, but they struggle with the flaw of their fundamental
  paradigm.
  -  It's hard to change what you're doing when you aren't changing
    your context - where you're /coming from/.
  - Some parents opt their children out of school entirely, in favor
    of home schooling and other forms of /unschooling/.
  - But there are a few alternative schools which do /not/ operate
    inside of the Dominator Model
  -  for example Montessori Schools.

- Lynn :: I love Montessori Schools, but tell us why you think they're
  important.

- Greg :: Maria Montessori is a hero of humanity!
  -  She believed that children were naturally motivated to learn,
    without any need to compell them.
  -  She also believed that "children are better at learning than
    teachers are at teaching".
  -  Instead of developing /a teaching system/, she developed /a
    learning system/
    - a classroom full of interactive learning materials designed to
      provide natural feedback to a child working with them.
    - with a guide, a trained facilitator, rather than a teacher.
  - A key distinction is that a facilitator is a resource for the
    child, not an intermediary like a teacher.
    - A facilitator sits to the side, rather than standing in front.

- Lynn :: How available is Montessori Education today?

- Greg :: Montessori started her schools in some of the poorest areas
  of her day, including the vast slums of Rome and of Calcutta - then
  the administrative capital of India: This was possible because
  Montessori schools are designed to be cheaper to run than
  conventional schools!  And even with the poorest students,
  Montessori schools consistently produced better results than regular
  schools.  Yet somehow after her death the Montessori schools
  available to the poor have largely disappeared.  Most Montessori
  Schools today are expensive private schools serving the wealthy
  elite.  And indeed, many of today's elite come from Montessori
  Schools, like the founders of Google.  Note that this sort of change
  is a classic example of /Dominator Culture/ in action!

- Lynn :: Do you have a plan for fixing this?

- Greg :: Yes, but first there's one more system I'd like to mention,
  /Mastery Learning/.
  - I encountered this at the University of California at San Diego in
    the late 1970s and early 1980s
    - I later learned that it was being tried out by innovative
      educators worldwide at that time, but I'll speak from my
      experience at UC San Diego.
  - In Mastery Education the material to be learned is divided up into
    logical modules accompanied by self-paced projects and
    self-assessment tests.
    - The projects ccould be done alone or with partners but each
      learner had to show individual mastery for their project to pass.
    - The tests were comprehensive and extremely challenging and learners were required to score 100% to pass!
  - Despite the unusually challenging projects and tests, the learners loved both!
    - The projects and tests did not go on any permanent record.
    - They were only there to assist the student in mastering the material of the module.
    - If they failed a test, they could take a different, equally
      comprehensive version after another day of studying.
  - We ran the Mastery Course alongside the traditional "Lecture & Recitation" Course for a year,
    - About 15% of the students in the traditional course got an "A".
    - 80% of the Mastery students got an "A"!
    - And detailed examination showed that the Mastery Students with
    - The traditional courses were discontinued!      
- Greg :: The Mastery Courses had an additional resource:
  - Students who completed the course were invited to become /Peer
    Facilitators/ to assist the students in the course the next year.
  - We found that these /Peer Facilitators/ were much better at assisting students who were
    have trouble with the material than our professors!    
  - The /Peer Facilitators/ also contributed major improvements to the
    learning materials, including submitting the questions for the
    tests!
  - Do you see /Partnership Culture/ involved here?

- Lynn :: Defintely!  So is your plan to create new schools combining
  the Montessori and Mastery systems?  That sounds great but also
  pretty ambitious!

- Greg :: Well, physical classrooms have a lot of overhead, and
  there's no way that they can cover all of the subjects
  which Learners want to Learn.
  - Education is increasingly moving online.
    - Most online educational materials follow a top-down model,
    - However, they can often be adapted into Learner-centric context
      by accompanying them with
      - Self-Paced interactive materials
      - Learning Partners
      - Peer Facilitators
      - etc.
  - Learners who complete any of our curricula will be offered the
    opportunity to be Peer Facilitators for the next set of learners!
  - We have built-in extensive mechanisms for learners and peer
    facilitators to provide feedback on all of our materials
  - Learners, and especially Peer Facilitators will be invited to help
    find, create and revise all of our materials - as well as to
    create new curricula!

- Lynn :: I like the idea of that, but I'm not so sure that someone
  who just learned something is a substitute for an actual expert!

- Greg :: Oh, we'll have experts, but their job is to /facilitate/ the
  development process rather than to control it top-down.
  -  /The League of Extraordinary Learners/ is new and in rapid
    development.
  - We invite you to to participate!
  - Please visit our website at: T-L-O-E-L DOT org.

- Lynn :: I really like what you say, Greg.  I look forward to working
  with you on further videos.
- Lynn [without Greg] :: Stay tuned!  More videos to come.  Please
  consider what we talked about in this one and figure out if you are
  operating from a /Dominator Model/ or a /Partnership Model/ and
  which one do you want to live in to?

** References

- [[https://en.wikipedia.org/wiki/Dominator_culture][Wikipedia: Dominator Culture]]
- [[https://en.wikipedia.org/wiki/Prussian_education_system][Prussian education system]]
- [[https://en.wikipedia.org/wiki/Montessori_education][Wikipedia: Montessori Education]]
- [[https://en.wikipedia.org/wiki/Mastery_learning][Wikipedia: Mastery Learning]]
- [[https://en.wikipedia.org/wiki/Unschooling][Wikipedia: Unschooing]]

** Currently Deleted Scenes

Greg brought back having Lynn look up Paradigm and Model!
