* Creating LOEL Curricula

LOEL Curricula can come about via many paths, many of which involve chaos and
serendipity. What follows is a description of a normative path for intentionally
creating a LOEL Curriculum.

** What is a LOEL Curriculum?

A LOEL Curriculum consists of materials and resources for Learners to study,
practice and master a particular area of human knowledge or distinctions.

A LOEL Curriculum is Learner Centric
- bottom-up, not top-down
- flexible and self-paced
- incorporating feedback and self-assessment components
- mixing theory and practice synergistically
- creating competence and then mastery
      - creating a platform for further learning
      - part of exponential life-long learning
- Directly supportable by Peer Facilitators
      - recent students contribute back
            - supporting new students
            - improving the materials
- Indirectly supportable by Experts
      - supporting new Peer Facilitators
      - vetting the materials

** Who Might Create a LOEL Curriculum and Why?

A Curriculum of the League of Extraordinary Learners is created by enthusiasts
for a topic. These could be newcomers who want to learn the topic, advanced
students who've recently studied the area or experts in the field. The keys are
that they love it and they want to make it accessible for newcomers.

** How Does a LOEL Curriculum Develop?

Normatively, a LOEL Curriculum is started by assembling and organizing a
collection of the best materials for learning the topic
- Books
- Videos
- Immersive models
- etc.

A all development is done by Participants
- Learners and Peer Facilitators
- Sometimes other enthusiasts
- Guided by experts

Currently we store the materials for most LOEL curricula in a Git Repository and
make them available through GitHub, GitLab, etc.

In the future, the materials will be stored in a Wicci System.

We call the initial state of a LOEL Curriculum a Directory of Resources.

The LOEL Directory grows as the participants
- Upgrade the links to more and better materials
- Add and contribute to FAQ nodes for all links

The LOEL Curriculum develops by
- Upgrading the LOEL Directory
- Adding self-assessment tools
- Adding practical exercises
- Creating new materials
      - to complement external resources
      - as upgrades to or enrichment of external resources
      - Articles, Interactive Notebooks, Immersive Environments, etc.
