* Creating and Developing LOEL Curricula

[[file:../../README.org][Leage of Extraordinary Learners]] Curricula can come about via many paths, many of
which involve chaos and serendipity. What follows is a description of a
normative path for intentionally creating a new LOEL Curriculum. May this
provide useful guidance rather than unhelpful constraints!

** What is a LOEL Curriculum?

A /LOEL Curriculum/ consists of materials and resources for Learners to study,
practice and master a particular area of human knowledge or distinctions.

A /LOEL Curriculum/ is /Learner Centric/
- more bottom-up than top-down
- flexible and self-paced
      - providing multiple paths and optional elements
- incorporating feedback and self-assessment components
- a synergistic mix of theory and practice
- designed to creating competence and then mastery
      - creating a platform for further learning
      - part of exponential life-long learning
- Directly supportable by Peer Facilitators
      - recent students contribute back
            - supporting new students
            - improving the materials
- Indirectly supportable by Experts
      - supporting new Peer Facilitators
      - vetting the materials

** Who Might Create a LOEL Curriculum and Why?

A Curriculum of the League of Extraordinary Learners is created by enthusiasts
for a topic. These could be newcomers who want to learn the topic, advanced
students who've recently studied the area or experts in the field. The keys are
that they love it and they want to make it accessible for newcomers.

** How Does a LOEL Curriculum Develop?

Normatively, a LOEL Curriculum begins as a LOEL Directory.

A LOEL Directory is created by assembling and organizing a
collection of the best materials for learning the topic
- Books, Articles, Podcasts, Videos
- Websites and Webpages
- Immersive models, e.g. Simulations and Games
- etc.

All development is done by /Participants/
- /Learners/ and /Peer Facilitators/
- Sometimes /Other Enthusiasts/
- Guided by Experts

Currently we store the materials for most LOEL Curricula in a /Git Repository/
and make them available through /GitHub/, /GitLab/, etc.

In the future, the materials will live in a /Wicci System/.

The LOEL Directory grows as the participants
- Upgrade the links to more and better materials
- Add and contribute to FAQ nodes for all links

The LOEL Curriculum develops by
- Upgrading the LOEL Directory
- Adding self-assessment tools
- Adding practical exercises
- Creating new materials
      - to complement external resources
      - as upgrades to or enrichment of external resources
      - Articles, Interactive Notebooks, Immersive Environments, etc.
      - Creating and upgrading FAQ nodes for all elements
